thread 'main' panicked at src/main.rs:404:10:
called `Result::unwrap()` on an `Err` value: File(Os { code: 5, kind: Uncategorized, message: "Input/output error" }, ErrorBacktrace)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
