Traceback (most recent call last):
  File "/lfs/koff9454.ui/projects/plc_runtime_fuzzer/code_analysis/src/main.py", line 26, in <module>
    code = Path(args.file).read_bytes()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lfs/koff9454.ui/miniconda3/envs/plc/lib/python3.11/pathlib.py", line 1050, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lfs/koff9454.ui/miniconda3/envs/plc/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'runs.st'
Traceback (most recent call last):
  File "/lfs/koff9454.ui/projects/plc_runtime_fuzzer/runtime/../code_analysis/src/main.py", line 26, in <module>
    code = Path(args.file).read_bytes()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lfs/koff9454.ui/miniconda3/envs/plc/lib/python3.11/pathlib.py", line 1050, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lfs/koff9454.ui/miniconda3/envs/plc/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lfs/koff9454.ui/projects/plc_runtime_fuzzer/code_analysis/src/programs/complex/runs/runs.st'
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'harness': No such file or directory
cp: cannot stat 'inputs.dict': No such file or directory
cp: cannot stat 'inputs.dict': No such file or directory
cp: cannot stat 'inputs.dict': No such file or directory
cp: cannot stat 'indir': No such file or directory
cp: cannot stat 'indir': No such file or directory
